import React, { useMemo } from "react";
import { formatTimeline } from "@/lib/analyze";
import type { AnalysisData, Proposal } from "../types";

function StatCard({ label, value }: { label: string; value: string | number | React.ReactNode }) {
  return (
    <div className="rounded border px-4 py-3 text-sm text-gray-700 min-w-[160px] bg-white flex-shrink-0">
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="font-semibold mt-1 break-words">{value}</div>
    </div>
  );
}

export function Overview({
  analysisData,
  budgetSummary,
  timelineSummaryRaw,
  recommendedCount,
  analysedCount
}: {
  analysisData: AnalysisData;
  proposals: Proposal[];
  budgetSummary: string;
  timelineSummaryRaw: string;
  recommendedCount: number;
  analysedCount: number;
}) {
  const rfpSummary = analysisData.rfp_summary;
  const finalRec = analysisData.final_recommendation;
  const timelineSummaryObj = useMemo(() => formatTimeline(timelineSummaryRaw), [timelineSummaryRaw]);
  const anlysisTitle = analysisData.rfp_title;

  return (
    <>
      <div className="flex items-center gap-3">
        <div className="flex-1">
          <h1 className="text-2xl font-semibold break-words">RFP Proposal Comparative Analysis</h1>
          <div className="text-sm text-gray-500 mt-1 break-words">
            {anlysisTitle}
          </div>
        </div>
      </div>

      <div className="flex flex-wrap items-center mt-4 gap-3">
        <StatCard label="Budget" value={budgetSummary} />
        <StatCard label="Timeline" value={<span title={timelineSummaryObj.full}> {timelineSummaryObj.short} </span>} />
        <StatCard label="Proposals Recommended" value={recommendedCount} />
        <StatCard label="Proposals Analysed" value={analysedCount} />
      </div>

      <div className="mb-6 mt-6">
        <div className="rounded border p-4 bg-white">
          <h2 className="font-medium">Executive Summary</h2>
          <p className="mt-2 text-sm text-gray-700">
            {rfpSummary?.executive_summary || `This analysis evaluates ${analysedCount} vendor proposals against the requirements outlined in your RFP. Results below are generated by the analyzer and mapped to a deterministic display.`}
          </p>
        </div>
      </div>

      <div className="mb-6">
        <div className="rounded-lg border border-gray-200 p-6 bg-white shadow-sm">
          <h3 className="text-lg font-semibold mb-4">Final Recommendation</h3>
          <div className="space-y-4">
            {finalRec?.comparative_analysis ? (
              <>
                <div className="p-4 rounded-lg bg-slate-50">
                  <p className="text-sm text-gray-700 whitespace-pre-wrap">
                    {finalRec.comparative_analysis}
                  </p>
                </div>

                {finalRec.key_findings?.length ? (
                  <div className="p-4 rounded-lg bg-slate-50">
                    <h4 className="font-medium text-sm mb-2">Key Findings</h4>
                    <ul className="space-y-2 text-sm text-gray-700">
                      {finalRec.key_findings.map((f, i) => <li key={i}>• {f}</li>)}
                    </ul>
                  </div>
                ) : null}

                {finalRec.recommended_proposal ? (
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <div className="text-xs text-gray-600 mb-1">Recommended Proposal</div>
                      <div className="text-sm font-medium">{finalRec.recommended_proposal}</div>
                    </div>
                    <div>
                      <div className="text-xs text-gray-600 mb-1">Recommended Organization</div>
                      <div className="text-sm font-medium">{finalRec.recommended_organization}</div>
                    </div>
                  </div>
                ) : null}
              </>
            ) : (
              <>
                {finalRec ? (
                  <div className="p-4 rounded-lg bg-slate-50">
                    <p className="text-sm text-gray-700">
                      {finalRec.final_recommendation || "No final recommendation text available."}
                    </p>
                  </div>
                ) : (
                  <div className="text-sm text-gray-500">No recommendation available.</div>
                )}
              </>
            )}
          </div>
        </div>
      </div>
    </>
  );
}