export function AIDisclaimer() {
  return (
    <div className="mt-6 pt-4 border-t border-gray-200">
      <p className="text-sm text-muted-foreground text-center mb-3">
        Results are generated by AI and may not always be accurate.
      </p>
    </div>
  );
}